name: cellove_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  gap: ^2.0.0
  percent_indicator: ^4.0.1
  google_maps_flutter: ^2.1.2
  http: ^0.13.4
  get: ^4.1.4
#  dio: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/celeb_img/
    - assets/images/membership_img/

  fonts:

    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Bold.otf
        - asset: assets/fonts/GeneralSans-Italic.otf
        - asset: assets/fonts/GeneralSans-Medium.otf
        - asset: assets/fonts/GeneralSans-Regular.otf
        - asset: assets/fonts/GeneralSans-Semibold.otf

    - family: DoHyeon-Regular
      fonts:
        - asset: assets/fonts/DoHyeon-Regular.ttf

    - family: Gugi-Regular
      fonts:
        - asset: assets/fonts/Gugi-Regular.ttf